#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <flippy_sensors_icons.h>

int32_t flippy_sensors_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm flippy_sensors!");

    return 0;
}
